### ISSUE TITLE
ngx-progressbar relies on @angular/http

### ISSUE THREAD

**Issue by KyleMulder** [MurhafSousli/ngx-progressbar#61]
**I'm submitting a bug report** 

If you remove the use of the old `@angular/http`, ngx-progressbar complains that it can't find the `BrowserXhr` class.

**Comment by MurhafSousli** [comment]
Hi @KyleMulder, 
The library does not use  `Http` nor `HttpClient`.
Are you getting an error? please add more details.

**Comment by KyleMulder** [comment]
`node_modules/ngx-progressbar/src/services/browser-xhr.provider.d.ts (1,28): Cannot find module '@angular/http'`

**Comment by fchiumeo** [comment]
post full example

**Comment by KyleMulder** [comment]
I don't need to post an example, the issue can be seen in your file:

https://github.com/MurhafSousli/ngx-progressbar/blob/master/src/services/browser-xhr.provider.ts

**Comment by fchiumeo** [comment]
https://github.com/MurhafSousli/ngx-progressbar#automagic-loading-bar
httpclient(@angular/common/http) use NgProgressInterceptor
http(@angular/http) use NgProgressBrowserXhr

**Comment by MurhafSousli** [comment]
@KyleMulder I think @fchiumeo gave the answer. closing this but feel free to continua the discussion

**Comment by fchiumeo** [comment]
ngx-progressbar has support for the two http(http and httpclient), I think for compatibility.
But I can not quite understand what the issue would be
ps: or you do not have the package angular/http in your package.json ?

**Comment by MurhafSousli** [comment]
@fchiumeo Do you mean the peerDependency https://github.com/MurhafSousli/ngx-progressbar/blob/9dd7621b4563e1b844910697b4a32097e5cc1fe9/package.json#L42 .. I think it shouldn't be there!

**Comment by fchiumeo** [comment]
i guess
@KyleMulder test the new version

**Comment by Conradolucas** [comment]
not working in v 2.0.8,
same error reported by @KyleMulder

**Comment by Conradolucas** [comment]
I'm following the recommendations.

`"dependencies": {
    "@angular/core": "4.4.4",
    "@angular/animations": "4.4.4",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "4.4.4",
    "@angular/forms": "4.4.4",
    "@angular/platform-browser": "4.4.4",
    "@angular/platform-browser-dynamic": "4.4.4",
    "@angular/router": "4.4.4",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.4",
    "angular-highcharts": "^3.4.8",
    "bootstrap": "3.3.7",
    "core-js": "^2.5.1",
    "font-awesome": "^4.7.0",
    "highcharts": "^6.0.1",
    "ngx-perfect-scrollbar": "^4.8.4",
    "ngx-progressbar": "2.0.8",
    "npm-font-open-sans": "^1.1.0",
    "rxjs": "5.4.3",
    "zone.js": "0.8.17"
  }`

**Comment by Romain-P** [comment]
still have the error on angular 8

**Comment by suhaskurade8** [comment]
I'm having the same issue in Angular 9
