### ISSUE TITLE
Upgrade 4.3.0 to 5.0.1: Object is not a function error

### ISSUE THREAD

**Issue by stevenvanryckeghem** [MurhafSousli/ngx-progressbar#175]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ X ] question
```

### Versions
Angular 5 / 6
ngx-progressbar/core,http,router: 5.0.1
node 8.9.4
npm 5.6.0

### Repro steps
Using the installation steps of "automagically progress bars" for router & http modules. 
Works in version 4.3.0 but when upgrading to 5.0.1 we get an error.
Tried to make a Stackblitz to reproduce but it actually worked there (same config)

### The log given by the failure
![image](https://user-images.githubusercontent.com/5240110/40224098-6994bc1c-5a85-11e8-9ed3-673862bea3e2.png)

![image](https://user-images.githubusercontent.com/5240110/40224138-8fac935c-5a85-11e8-95cf-870e8b155721.png)

Any ideas? Something has changed from 4.3.0 to 5.0.1.

Thx in advance!

**Comment by MurhafSousli** [comment]
Hey @stevenvanryckeghem Nothing changed really! just updated the build system to make a compatible build with Angular 6. I cannot determine what is wrong without a reproduction.

**Comment by YoussefTizi** [comment]
i have the same issue any solution ?? to resolve this issue

**Comment by MurhafSousli** [comment]
@YoussefTizi @stevenvanryckeghem which Angular version are you using? `5.0.1` is for angular 6 and will not work on angular 5

**Comment by MurhafSousli** [comment]
The latest version for Angular 5 is `4.3.0`

**Comment by stevenvanryckeghem** [comment]
@MurhafSousli ok, I'll try again on Angular 6. Maybe adopt the docs from 'This is the documentation for ngx-progressbar version 4.x (Angular >= 5) and version 5.x (Angular >= 6)' to 'This is the documentation for ngx-progressbar version 4.x (Angular **>= 5 < 6**) and version 5.x (Angular >= 6)' or something like that. It's a bit confusing :)

**Comment by MurhafSousli** [comment]
@stevenvanryckeghem It is mentioned in the changelog
