### ISSUE TITLE
how to use automagic loading with @ngx-progressbar/core

### ISSUE THREAD

**Issue by kiranirabatti** [MurhafSousli/ngx-progressbar#233]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> ngx-progressbar-core has no exported member 'NgProgressBrowserXhr'
- [ ] feature request -> need progress bar on each http request
- [ ] question -> how to use the automagic loading with @ngx-progressbar/core
```

### OS and Version?
> Windows 10.

### Versions
angular cli - 6.0.1
node - 9.8.0
@ngx-progressbar/core - 5.2.1

### Repro steps
Try to use 
import { NgProgressModule, NgProgressBrowserXhr } from '@ngx-progressbar/core';
above line in app.module.ts, it will give an error saying ngx-progressbar-core has no exported member 'NgProgressBrowserXhr'

### The log given by the failure
ERROR in src/app/app.module.ts(9,28): error TS2305: Module '"E:/ProjectName/node_modules/@ngx-progressbar/core/ngx-progressbar-core"' has no exported member 'NgProgressBrowserXhr'.

### Desired functionality
I want to show the progress bar on each network call

### Mention any other details that might be useful
May be the steps for automagic loading are changed, please help me with this.

**Comment by MurhafSousli** [comment]
Please add a repro [stackblitz](https://stackblitz.com/edit/ngx-progressbar)

**Comment by kiranirabatti** [comment]
got it, I was trying to use incompatible code, found your new one in your provided link which works with angular 6.0.1, thanx.
